services:    
  redis:
    image: redis:7.2-alpine3.20
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    networks:
      - bff-api-pokemon
    



networks:
  bff-api-pokemon:
  
volumes:
  redis-data:
