services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-bff-api-pokemon
    container_name: backend-bff-api-pokemon
    ports:
      - "${PORT}:3000"
    environment:
      - POKEMON_API_BASE_URL=${POKEMON_API_BASE_URL}
      - PORT=${PORT}
    
